In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno
#%matplotlib inline
import seaborn as sns


from sklearn.preprocessing import PolynomialFeatures

In [2]:
X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
poly = PolynomialFeatures(2)
poly

PolynomialFeatures()

In [4]:
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [5]:
det = {
    'show_id' : ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9'],
    'type' : ['TV Show', 'Movie', 'Movie', 'TV Show', '?','TV Show', 'Movie', 'Movie', 'TV Show'],
    'title' : ['rent', '???', 'marche', 'ecole', 'defense', 'vie', 'zero', 'rent', 'vie'],
    'director' : ['Abdou', 'Grau', 'Chan', 'Acker','?', 'rrr', 'Acker','Marcel', 'Labrador'],     
    'country' : ['Brazil', 'Mexico', 'UK', 'US', 'US','UK','UK','???','UK'], 
     'manque' : [139, np.nan, np.nan, np.nan, np.nan, np.nan,np.nan, np.nan, np.nan],
    'added' : [12.8, 17.8, 1007, 32, 1720.4, 4587, 1001.4,28.45, 37845.9],     
    'release_year' : [2020, 2016, 2011, 2009,2008, 2010, 2017, 2009, 2022],    
    'rating' : ['TV-MA', 'TV-MA', 'R', 'PG-13', 'PG-13', 'RP-12','PGI-17', 'TV-MO', 'S'],   
    'duration' : [90.5, 93, 78, 80,123, 75.33, 115, 86, 125],    
    'averageRating' : [5.7, np.nan, 10.5, 6.2, 6.2, np.nan, 10, 3.5, 9],
    'is_action' : [True, True, False, True, False, False,True, False, False],
    'duree' : [139, 90, np.nan, 155, 133, np.nan,165, 120, 159],
    'Nb_entree' : [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan,165, np.nan, np.nan],
    'numVotes' : [1670, 208, np.nan,'!', np.nan, 817, 163, 33204, 1266]}

In [6]:
# creating a Dataframe object 
det = pd.DataFrame(det)

In [7]:
det

show_id     type    title  director country  manque     added  release_year  \
0      s1  TV Show     rent     Abdou  Brazil   139.0     12.80          2020   
1      s2    Movie      ???      Grau  Mexico     NaN     17.80          2016   
2      s3    Movie   marche      Chan      UK     NaN   1007.00          2011   
3      s4  TV Show    ecole     Acker      US     NaN     32.00          2009   
4      s5        ?  defense         ?      US     NaN   1720.40          2008   
5      s6  TV Show      vie       rrr      UK     NaN   4587.00          2010   
6      s7    Movie     zero     Acker      UK     NaN   1001.40          2017   
7      s8    Movie     rent    Marcel     ???     NaN     28.45          2009   
8      s9  TV Show      vie  Labrador      UK     NaN  37845.90          2022   

   rating  duration  averageRating  is_action  duree  Nb_entree numVotes  
0   TV-MA     90.50            5.7       True  139.0        NaN     1670  
1   TV-MA     93.00            NaN       True   90.0        NaN      208  
2       R     78.00           10.5      False    NaN        NaN      NaN  
3   PG-13     80.00            6.2       True  155.0        NaN        !  
4   PG-13    123.00            6.2      False  133.0        NaN      NaN  
5   RP-12     75.33            NaN      False    NaN        NaN      817  
6  PGI-17    115.00           10.0       True  165.0      165.0      163  
7   TV-MO     86.00            3.5      False  120.0        NaN    33204  
8       S    125.00            9.0      False  159.0        NaN     1266

In [8]:
 det["duration" + "_Bucket"] = det["duration"] // 2 * 1

In [9]:
det

show_id     type    title  director country  manque     added  release_year  \
0      s1  TV Show     rent     Abdou  Brazil   139.0     12.80          2020   
1      s2    Movie      ???      Grau  Mexico     NaN     17.80          2016   
2      s3    Movie   marche      Chan      UK     NaN   1007.00          2011   
3      s4  TV Show    ecole     Acker      US     NaN     32.00          2009   
4      s5        ?  defense         ?      US     NaN   1720.40          2008   
5      s6  TV Show      vie       rrr      UK     NaN   4587.00          2010   
6      s7    Movie     zero     Acker      UK     NaN   1001.40          2017   
7      s8    Movie     rent    Marcel     ???     NaN     28.45          2009   
8      s9  TV Show      vie  Labrador      UK     NaN  37845.90          2022   

   rating  duration  averageRating  is_action  duree  Nb_entree numVotes  \
0   TV-MA     90.50            5.7       True  139.0        NaN     1670   
1   TV-MA     93.00            NaN       True   90.0        NaN      208   
2       R     78.00           10.5      False    NaN        NaN      NaN   
3   PG-13     80.00            6.2       True  155.0        NaN        !   
4   PG-13    123.00            6.2      False  133.0        NaN      NaN   
5   RP-12     75.33            NaN      False    NaN        NaN      817   
6  PGI-17    115.00           10.0       True  165.0      165.0      163   
7   TV-MO     86.00            3.5      False  120.0        NaN    33204   
8       S    125.00            9.0      False  159.0        NaN     1266   

   duration_Bucket  
0             45.0  
1             46.0  
2             39.0  
3             40.0  
4             61.0  
5             37.0  
6             57.0  
7             43.0  
8             62.0

In [10]:
pd.pandas.set_option('display.max_columns', None)
pd.pandas.set_option('display.max_rows', None)

In [11]:
np.linspace(0.01, 0.05, 10)

array([0.01      , 0.01444444, 0.01888889, 0.02333333, 0.02777778,
       0.03222222, 0.03666667, 0.04111111, 0.04555556, 0.05      ])

In [12]:
# Create first data frame
df1_Test = pd.DataFrame({
   'key1': ['A', 'B', 'C', 'D'],
   'key2': ['W', 'X', 'Y', 'Z'],
   'value1': [1, 2, 3, 4],
   'value2': [5, 6, 7, 8]
})

# Create second data frame
df2_Test = pd.DataFrame({
   'key1': ['A', 'B', 'C', 'E'],
   'key2': ['W', 'X', 'Z', 'Y'],
    'value1': [0, 25, 3, 13],
   'value3': [9, 10, 11, 12],
   'value4': [13, 14, 15, 16]
})

In [13]:
df1_Test

key1 key2  value1  value2
0    A    W       1       5
1    B    X       2       6
2    C    Y       3       7
3    D    Z       4       8

In [14]:
df2_Test

key1 key2  value1  value3  value4
0    A    W       0       9      13
1    B    X      25      10      14
2    C    Z       3      11      15
3    E    Y      13      12      16

In [15]:
# Merge data frames on multiple columns
merged_df = pd.merge(df1_Test, df2_Test, on=['key1', 'key2', 'value1'], how='outer')

In [16]:
merged_df

key1 key2  value1  value2  value3  value4
0    A    W       1     5.0     NaN     NaN
1    B    X       2     6.0     NaN     NaN
2    C    Y       3     7.0     NaN     NaN
3    D    Z       4     8.0     NaN     NaN
4    A    W       0     NaN     9.0    13.0
5    B    X      25     NaN    10.0    14.0
6    C    Z       3     NaN    11.0    15.0
7    E    Y      13     NaN    12.0    16.0

In [17]:
np.unique(merged_df.value1)

array([ 0,  1,  2,  3,  4, 13, 25], dtype=int64)

In [18]:
len(np.unique(merged_df.value1))

7

In [19]:
merged_df.value1[merged_df.value1 > 0]

0     1
1     2
2     3
3     4
5    25
6     3
7    13
Name: value1, dtype: int64

In [20]:
merged_df.value1[merged_df.value1 > 0].max()

25

In [21]:
merged_df["key2"]

0    W
1    X
2    Y
3    Z
4    W
5    X
6    Z
7    Y
Name: key2, dtype: object

In [22]:
 np.where(merged_df['value2'].isna(), 0, 1)

array([1, 1, 1, 1, 0, 0, 0, 0])

In [23]:
print(pd.crosstab(merged_df["key2"], np.where(merged_df['value2'].isna(), 0, 1)))

col_0  0  1
key2       
W      1  1
X      1  1
Y      1  1
Z      1  1


In [24]:
merged_df

key1 key2  value1  value2  value3  value4
0    A    W       1     5.0     NaN     NaN
1    B    X       2     6.0     NaN     NaN
2    C    Y       3     7.0     NaN     NaN
3    D    Z       4     8.0     NaN     NaN
4    A    W       0     NaN     9.0    13.0
5    B    X      25     NaN    10.0    14.0
6    C    Z       3     NaN    11.0    15.0
7    E    Y      13     NaN    12.0    16.0

In [25]:
###################################################################################

In [26]:
#dataFrame=pd.read_excel('C:/Training_DataScientist_MachineLearning/Sprint5 Machine_Learning_2_de_4/Classification avancée/hiva.xlsx')#, sep=";")

In [27]:
# Create first data frame
dataFrame_1 = pd.DataFrame({
    'unnamed': [0, 1, 2, 3],
   'key1': ['A', 'B', 'C', 'D'],
   'key2': ['W', 'X', 'Y', 'Z'],
   'value1': [1, np.nan, 3, 4],
   'value2': [5, 6, 7, 8]
})

# Create second data frame
dataFrame_2 = pd.DataFrame({
   'unnamed': [0, 1, 2, 3], 
   'key1': ['A', 'B', 'a', np.nan],
   'key2': ['W', np.nan, 'Z', 'Y'],
    'value1': [0, np.nan, 3, 13],
   'value3': [4, 10, 17, 12],
   'value4': [13, 14, 15, 16]
})

In [28]:
dataFrame_1

unnamed key1 key2  value1  value2
0        0    A    W     1.0       5
1        1    B    X     NaN       6
2        2    C    Y     3.0       7
3        3    D    Z     4.0       8

In [29]:
dataFrame_1.set_index('unnamed', inplace=True)

In [30]:
dataFrame_1

key1 key2  value1  value2
unnamed                          
0          A    W     1.0       5
1          B    X     NaN       6
2          C    Y     3.0       7
3          D    Z     4.0       8

In [31]:
dataFrame_2

unnamed key1 key2  value1  value3  value4
0        0    A    W     0.0       4      13
1        1    B  NaN     NaN      10      14
2        2    a    Z     3.0      17      15
3        3  NaN    Y    13.0      12      16

In [32]:
dataFrame_2.dropna(axis=0, how='any', inplace=False)

unnamed key1 key2  value1  value3  value4
0        0    A    W     0.0       4      13
2        2    a    Z     3.0      17      15

In [33]:
dataFrame_2

unnamed key1 key2  value1  value3  value4
0        0    A    W     0.0       4      13
1        1    B  NaN     NaN      10      14
2        2    a    Z     3.0      17      15
3        3  NaN    Y    13.0      12      16

In [34]:
dataFrame_2.dropna(axis=0, how='any', inplace=True)

In [35]:
dataFrame_2

unnamed key1 key2  value1  value3  value4
0        0    A    W     0.0       4      13
2        2    a    Z     3.0      17      15

In [36]:
dataFrame_2.set_index('unnamed', inplace=True)

In [37]:
dataFrame_2

key1 key2  value1  value3  value4
unnamed                                  
0          A    W     0.0       4      13
2          a    Z     3.0      17      15

In [38]:
dataFrame_2.reset_index(drop=True, inplace=True)

In [39]:
dataFrame_2

key1 key2  value1  value3  value4
0    A    W     0.0       4      13
1    a    Z     3.0      17      15

In [40]:
#df.reset_index(drop=True)

In [41]:
#dataFrame_3=dataFrame_2.dropna(axis=0, how='any', inplace=False)

In [42]:
#dataFrame_3

In [43]:
neighbours = np.arange(1,25)
train_accuracy = np.empty(len(neighbours))
test_accuracy = np.empty(len(neighbours))

In [44]:
train_accuracy

array([-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ,  0.5 , -0.25,  0.25,
        0.  ,  0.5 ,  0.25,  0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ,
       -0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25])

In [45]:
test_accuracy

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.79103119e-307,
       7.56587585e-307, 1.37961302e-306, 1.05699242e-307, 1.95821439e-306,
       1.60216183e-306, 1.78019625e-306, 8.45595292e-307, 1.33511290e-306,
       1.60218220e-306, 1.11261570e-306, 6.23059726e-307, 6.23053954e-307,
       9.34609790e-307, 8.45593934e-307, 9.34600963e-307, 1.37961777e-306,
       8.01097889e-307, 1.78021798e-306, 8.34451504e-308, 8.34402698e-308])

In [46]:
df = pd.DataFrame(np.arange(12).reshape(3, 4),
                  columns=['A', 'B', 'C', 'D'])

In [47]:
df

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [48]:
df = df.drop(['B'], axis=1)

In [49]:
df

A   C   D
0  0   2   3
1  4   6   7
2  8  10  11

In [50]:
df

A   C   D
0  0   2   3
1  4   6   7
2  8  10  11

In [51]:
import re

text = "Hello, world!"
pattern = r"(\w+), (\w+)"

match = re.search(pattern, text)

if match:
    # Récupérer toute la sous-chaîne correspondante
    full_match = match.group()
    print("Match complet:", full_match)  # Output: Hello, world!

    # Récupérer la première sous-chaîne capturée (groupe 1)
    first_group = match.group(1)
    print("Premier groupe:", first_group)  # Output: Hello

    # Récupérer la deuxième sous-chaîne capturée (groupe 2)
    second_group = match.group(2)
    print("Deuxième groupe:", second_group)  # Output: world


Match complet: Hello, world
Premier groupe: Hello
Deuxième groupe: world


In [53]:
import pandas as pd

# Exemple de DataFrame avec une colonne "Char"
data = {
    'Char': ['Hello thank you', ' world of famous', 'Python code', 'is not', 'awesome for all']
}
df = pd.DataFrame(data)

# Créer une chaîne de caractères contenant la concaténation de toutes les entrées de la colonne "Char"
CharChain = ' '.join(df['Char'])

# Afficher la chaîne résultante
print(CharChain)

Hello thank you  world of famous Python code is not awesome for all
